# Generated by Django 5.0.4 on 2024-06-19 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Дата обновления')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Дата обновления')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'db_table': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Дата обновления')),
                ('movie_name', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.IntegerField(default=100, verbose_name='Цена')),
                ('images', models.ImageField(max_length=500, upload_to='staticfiles', verbose_name='Изображение')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('date_created', models.DateField(null=True, verbose_name='Дата Создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='rent.moviecategory', verbose_name='Категория')),
            ],
            options={
                'db_table': 'Movies',
            },
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.movie')),
            ],
            options={
                'db_table': 'rent_showtime',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.showtime')),
            ],
            options={
                'db_table': 'rent_seat',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Дата обновления')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='rent.cart', verbose_name='Название')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.seat', verbose_name='Место')),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.showtime', verbose_name='Сеанс')),
            ],
            options={
                'db_table': 'CartItems',
            },
        ),
    ]
