# Generated by Django 5.0.4 on 2024-05-17 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_cart_created_at_alter_cart_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата Создания'),
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=2000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='cart',
            table='Carts',
        ),
        migrations.AlterModelTable(
            name='cartitems',
            table='CartItems',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='Movies',
        ),
        migrations.AlterModelTable(
            name='moviecategory',
            table='Categories',
        ),
    ]
