# Generated by Django 5.0.4 on 2024-05-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_movie_date_created_movie_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_created',
            field=models.DateField(null=True, verbose_name='Дата Создания'),
        ),
    ]
